config/routes.rb
Mustard::Application.routes.draw do |map|
  devise_for :users

  resources :test_targets

  resources :test_runs

  resources :test_cases do
    member do
      post :run
    end
  end

  resources :accounts

  resources :targets

  root :to => "test_cases#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :test_case
  
  belongs_to :user
end

app/models/run_job.rb
class RunJob
  def self.run(test_case_id)
    TestCase.find(test_case_id).run
  end
end

app/models/target.rb
class Target < ActiveRecord::Base
  attr_reader :selenium_driver
  alias :page :selenium_driver
  
  has_many :test_runs, :dependent => :destroy
  has_many :test_targets, :dependent => :destroy
  
  def name
    "#{os}:#{browser}:#{browser_version}"
  end
  
  
end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
  belongs_to :user
  attr_accessor :selenium_driver, :test_target_set
  alias_method :page, :selenium_driver
  
  belongs_to :account
  has_many :test_runs

  has_many :test_targets
  has_many :targets, :through => :test_targets
  
  def self.run_frequencies
    [["on demand", ""], ["10 minutes", "600"], ["1 hour", "3600"], ["5 hours", "18000"], ["1 day", "86400"], ["1 week", "604800"]]
  end

  def test_target_set=(value)
    self.test_targets.destroy_all
    value.each do |target_id|
      self.test_targets.build(:target_id => target_id)
    end
  end
  
  def test_target_set
    self.targets.collect do |target| target.id end
  end

  def run
    self.targets.each do |target|
      begin
        setup(target)
        # self.content.each_line do |cont|
          self.instance_eval(self.content)
        # end
        self.test_runs.create!(:job_id => page.session_id, :target => target)
        UserMailer.deliver_success(self)
      rescue Exception => e
        Exceptional.handle(e)
        logger.error "============== test case: #{self.id} target: #{target.id} had an error\n#{e.message}\n#{e.backtrace}"
        self.test_runs.create!(:job_id => page.session_id, :target => target, :error => "#{e.message}\n\n#{e.backtrace}")
        UserMailer.deliver_failure(self)
      ensure
        self.selenium_driver.close_current_browser_session if self.selenium_driver
        self.delay(:run_at => self.run_frequency.to_i.from_now).run unless self.run_frequency.blank?
      end
    end
  end
  
  def setup(target)
    @verification_errors = []
    @selenium_driver = Selenium::Client::Driver.new(
      :host => self.account.host,
      :port => self.account.port, 
      :browser => '{"username": "' + self.account.username + '",' +
                    '"access-key": "' + self.account.access_key + '",' +
                    '"os": "' + target.os + '",' +
                    '"browser": "' + target.browser + '",' +
                    '"browser-version": "' + target.browser_version + '",' +
                    '"public": true,' +
                    '"job-name": "' + self.name + '"}',
      :url => self.account.base_url,
      :timeout_in_second => self.account.timeout)
  
    @selenium_driver.start_new_browser_session
  end
  
end

app/models/test_run.rb
class TestRun < ActiveRecord::Base
  belongs_to :test_case
  belongs_to :target
  
  def url
    "http://saucelabs.com/jobs/#{self.job_id}"
  end
end

app/models/test_target.rb
class TestTarget < ActiveRecord::Base
  belongs_to :test_case
  belongs_to :target
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :accounts
  has_many :test_cases
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
    before_filter :authenticate_user!
    
    protected
    def begin_of_association_chain
      current_user
    end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/targets_controller.rb
class TargetsController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/controllers/test_cases_controller.rb
class TestCasesController < InheritedResources::Base
  before_filter :authenticate_user!  
  def run
    @test_case = TestCase.find(params[:id])
    @test_case.delay.run
    redirect_to :action => :show
  end
  
  protected
  def begin_of_association_chain
    current_user
  end
  
end

app/controllers/test_runs_controller.rb
class TestRunsController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/controllers/test_targets_controller.rb
class TestTargetsController < InheritedResources::Base
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :access_key
    = f.text_field :access_key
  .field
    = f.label :base_url
    = f.text_field :base_url
  .field
    = f.label :timeout
    = f.text_field :timeout
  .field
    = f.label :host
    = f.text_field :host
  .field
    = f.label :port
    = f.text_field :port
  = f.hidden_field :user_id, :value => current_user.id
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing Account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing Sauce Accounts

%table
  %tr
    %th Name
    %th Username
    %th Base url
    %th
    %th
    %th

  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.username
      %td= account.base_url
      %td= link_to 'Show', account
      %td= link_to 'Edit', edit_account_path(account)
      %td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New Account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p
  %b Name:
  = @account.name
%p
  %b Username:
  = @account.username
%p
  %b Access key:
  = @account.access_key
%p
  %b Base url:
  = @account.base_url
%p
  %b Timeout:
  = @account.timeout
%p
  %b Host:
  = @account.host
%p
  %b Port:
  = @account.port

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title
    = raw stylesheet_link_merged('screen', :media => 'screen, projection')
    = raw stylesheet_link_merged('print', :media => 'print')
    /[if lt IE 8]
      = raw stylesheet_link_merged('ie', :media => 'screen, projection')
    = csrf_meta_tag
  %body
    #container
      #header
        %h1.title Mustard - A Sauce Test Runner
      #sidebar
        %ul
          %li=link_to 'targets', targets_path
          %li=link_to 'accounts', accounts_path
          %li=link_to 'test cases', test_cases_path
          %li=link_to "log out", destroy_user_session_path
      #content
        - if notice
          %p.notice=notice
        -if alert
          %p.notice=alert
        = yield
      #footer

    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" }
    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" }
    = raw javascript_include_merged(:base)

app/views/targets/_form.html.haml
= form_for @target do |f|
  -if @target.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@target.errors.count, "error")} prohibited this target from being saved:"
      %ul
        - @target.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :os
    = f.text_field :os
  .field
    = f.label :browser
    = f.text_field :browser
  .field
    = f.label :browser_version
    = f.text_field :browser_version
  .actions
    = f.submit 'Save'

app/views/targets/edit.html.haml
%h1 Editing target

= render 'form'

= link_to 'Show', @target
\|
= link_to 'Back', targets_path

app/views/targets/index.html.haml
%h1 Listing Targets

%table
  %tr
    %th Os
    %th Browser
    %th Browser version
    %th
    %th
    %th

  - @targets.each do |target|
    %tr
      %td= target.os
      %td= target.browser
      %td= target.browser_version
      %td= link_to 'Show', target
      %td= link_to 'Edit', edit_target_path(target)
      %td= link_to 'Destroy', target, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New target', new_target_path

app/views/targets/new.html.haml
%h1 New target

= render 'form'

= link_to 'Back', targets_path

app/views/targets/show.html.haml
%p
  %b Os:
  = @target.os
%p
  %b Browser:
  = @target.browser
%p
  %b Browser version:
  = @target.browser_version

= link_to 'Edit', edit_target_path(@target)
\|
= link_to 'Back', targets_path

app/views/test_cases/_form.html.haml
= form_for @test_case do |f|
  -if @test_case.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@test_case.errors.count, "error")} prohibited this test_case from being saved:"
      %ul
        - @test_case.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :account_id, 'Account'
    = f.select :account_id, Account.all.collect {|a| [ a.name, a.id ] }, { :include_blank => true }
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :test_target_set, "Targets"
    = f.collection_select(:test_target_set, Target.all, :id, :name, {}, {:multiple => true, :size => 20})
  .field
    = f.label :run_frequency
    = f.select :run_frequency, ::TestCase.run_frequencies

  = f.hidden_field :user_id, :value => current_user.id
  .actions
    = f.submit 'Save'

app/views/test_cases/edit.html.haml
%h1 Editing Test Case

= render 'form'

= link_to 'Show', @test_case
\|
= link_to 'Back', test_cases_path

app/views/test_cases/index.html.haml
%h1 Listing Test Case

%table
  %tr
    %th Account
    %th Name
    %th
    %th
    %th

  - @test_cases.each do |test_case|
    %tr
      %td= test_case.account.name
      %td= test_case.name
      %td= link_to 'Show', test_case
      %td= link_to 'Edit', edit_test_case_path(test_case)
      %td= link_to 'Destroy', test_case, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Test Case', new_test_case_path

app/views/test_cases/new.html.haml
%h1 New Test Case

= render 'form'

= link_to 'Back', test_cases_path

app/views/test_cases/show.html.haml
%h1
  = @test_case.name
  = button_to 'Run', run_test_case_path(@test_case) 
%table
  %thead
    %th Job ID
    %th Target
    %th Run On
    %th &nbsp;
  %tfoot
  %tbody
    %tr
      %td= "Pending #{Delayed::Job.count(:conditions => ["locked_at IS NULL AND handler LIKE ? AND handler LIKE ?", "%TestCase%", "% id: \"#{@test_case.id}\"\n%"])}"
      %td= "Running #{Delayed::Job.count(:conditions => ["locked_at IS NOT NULL AND handler LIKE ? AND handler LIKE ?", "%TestCase%", "% id: \"#{@test_case.id}\"\n%"])}"
    - @test_case.test_runs.all(:order => "created_at DESC").each do |run|
      %tr{:class => run.error.blank? ? '' : 'failed' }
        %td=run.job_id
        %td=run.target.name
        %td=run.created_at
        %td=link_to "Sauce Link", run.url, :target => "blank"

%p
  %h2 Account:
  = @test_case.account.username if @test_case.account
%p
  %h2 Name:
  = @test_case.name
%p
  %h2 Content:
  =simple_format @test_case.content

%p
  %h2 Targets:
  %ul
    - @test_case.targets.each do |target|
      %li= target.name

= link_to 'Edit', edit_test_case_path(@test_case)
\|
= link_to 'Back', test_cases_path

app/views/test_runs/_form.html.haml
= form_for @test_run do |f|
  -if @test_run.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@test_run.errors.count, "error")} prohibited this test_run from being saved:"
      %ul
        - @test_run.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :test_case_id
    = f.text_field :test_case_id
  .field
    = f.label :target_id
    = f.text_field :target_id
  .field
    = f.label :job_id
    = f.text_field :job_id
  .actions
    = f.submit 'Save'

app/views/test_runs/edit.html.haml
%h1 Editing Test Run

= render 'form'

= link_to 'Show', @test_run
\|
= link_to 'Back', test_runs_path

app/views/test_runs/index.html.haml
%h1 Listing Test Runs

%table
  %tr
    %th Test case
    %th Target
    %th Job
    %th
    %th
    %th

  - @test_runs.each do |test_run|
    %tr
      %td= test_run.test_case_id
      %td= test_run.target_id
      %td= test_run.job_id
      %td= link_to 'Show', test_run
      %td= link_to 'Edit', edit_test_run_path(test_run)
      %td= link_to 'Destroy', test_run, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New test_run', new_test_run_path

app/views/test_runs/new.html.haml
%h1 New Test Run

= render 'form'

= link_to 'Back', test_runs_path

app/views/test_runs/show.html.haml
%p
  %b Test case:
  = @test_run.test_case_id
%p
  %b Target:
  = @test_run.target_id
%p
  %b Job:
  = @test_run.job_id

= link_to 'Edit', edit_test_run_path(@test_run)
\|
= link_to 'Back', test_runs_path

app/views/test_targets/_form.html.haml
= form_for @test_target do |f|
  -if @test_target.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@test_target.errors.count, "error")} prohibited this test_target from being saved:"
      %ul
        - @test_target.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :test_case_id
    = f.text_field :test_case_id
  .field
    = f.label :target_id
    = f.text_field :target_id
  .actions
    = f.submit 'Save'

app/views/test_targets/edit.html.haml
%h1 Editing Test Targets

= render 'form'

= link_to 'Show', @test_target
\|
= link_to 'Back', test_targets_path

app/views/test_targets/index.html.haml
%h1 Listing Test Targets

%table
  %tr
    %th Test case
    %th Target
    %th
    %th
    %th

  - @test_targets.each do |test_target|
    %tr
      %td= test_target.test_case_id
      %td= test_target.target_id
      %td= link_to 'Show', test_target
      %td= link_to 'Edit', edit_test_target_path(test_target)
      %td= link_to 'Destroy', test_target, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New test_target', new_test_target_path

app/views/test_targets/new.html.haml
%h1 New Test Targets

= render 'form'

= link_to 'Back', test_targets_path

app/views/test_targets/show.html.haml
%p
  %b Test case:
  = @test_target.test_case_id
%p
  %b Target:
  = @test_target.target_id

= link_to 'Edit', edit_test_target_path(@test_target)
\|
= link_to 'Back', test_targets_path